# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noone/projects/Chroma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noone/projects/Chroma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noone/projects/Chroma/CMakeFiles /home/noone/projects/Chroma/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noone/projects/Chroma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kernel.elf

# Build rule for target.
kernel.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel.elf
.PHONY : kernel.elf

# fast build rule for target.
kernel.elf/fast:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/build
.PHONY : kernel.elf/fast

chroma/kernel.o: chroma/kernel.c.o

.PHONY : chroma/kernel.o

# target to build an object file
chroma/kernel.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/kernel.c.o
.PHONY : chroma/kernel.c.o

chroma/kernel.i: chroma/kernel.c.i

.PHONY : chroma/kernel.i

# target to preprocess a source file
chroma/kernel.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/kernel.c.i
.PHONY : chroma/kernel.c.i

chroma/kernel.s: chroma/kernel.c.s

.PHONY : chroma/kernel.s

# target to generate assembly for a file
chroma/kernel.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/kernel.c.s
.PHONY : chroma/kernel.c.s

chroma/system/cpu.o: chroma/system/cpu.c.o

.PHONY : chroma/system/cpu.o

# target to build an object file
chroma/system/cpu.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/cpu.c.o
.PHONY : chroma/system/cpu.c.o

chroma/system/cpu.i: chroma/system/cpu.c.i

.PHONY : chroma/system/cpu.i

# target to preprocess a source file
chroma/system/cpu.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/cpu.c.i
.PHONY : chroma/system/cpu.c.i

chroma/system/cpu.s: chroma/system/cpu.c.s

.PHONY : chroma/system/cpu.s

# target to generate assembly for a file
chroma/system/cpu.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/cpu.c.s
.PHONY : chroma/system/cpu.c.s

chroma/system/drivers/keyboard.o: chroma/system/drivers/keyboard.c.o

.PHONY : chroma/system/drivers/keyboard.o

# target to build an object file
chroma/system/drivers/keyboard.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/drivers/keyboard.c.o
.PHONY : chroma/system/drivers/keyboard.c.o

chroma/system/drivers/keyboard.i: chroma/system/drivers/keyboard.c.i

.PHONY : chroma/system/drivers/keyboard.i

# target to preprocess a source file
chroma/system/drivers/keyboard.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/drivers/keyboard.c.i
.PHONY : chroma/system/drivers/keyboard.c.i

chroma/system/drivers/keyboard.s: chroma/system/drivers/keyboard.c.s

.PHONY : chroma/system/drivers/keyboard.s

# target to generate assembly for a file
chroma/system/drivers/keyboard.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/drivers/keyboard.c.s
.PHONY : chroma/system/drivers/keyboard.c.s

chroma/system/interrupts.o: chroma/system/interrupts.c.o

.PHONY : chroma/system/interrupts.o

# target to build an object file
chroma/system/interrupts.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/interrupts.c.o
.PHONY : chroma/system/interrupts.c.o

chroma/system/interrupts.i: chroma/system/interrupts.c.i

.PHONY : chroma/system/interrupts.i

# target to preprocess a source file
chroma/system/interrupts.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/interrupts.c.i
.PHONY : chroma/system/interrupts.c.i

chroma/system/interrupts.s: chroma/system/interrupts.c.s

.PHONY : chroma/system/interrupts.s

# target to generate assembly for a file
chroma/system/interrupts.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/interrupts.c.s
.PHONY : chroma/system/interrupts.c.s

chroma/system/memory/paging.o: chroma/system/memory/paging.c.o

.PHONY : chroma/system/memory/paging.o

# target to build an object file
chroma/system/memory/paging.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/paging.c.o
.PHONY : chroma/system/memory/paging.c.o

chroma/system/memory/paging.i: chroma/system/memory/paging.c.i

.PHONY : chroma/system/memory/paging.i

# target to preprocess a source file
chroma/system/memory/paging.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/paging.c.i
.PHONY : chroma/system/memory/paging.c.i

chroma/system/memory/paging.s: chroma/system/memory/paging.c.s

.PHONY : chroma/system/memory/paging.s

# target to generate assembly for a file
chroma/system/memory/paging.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/paging.c.s
.PHONY : chroma/system/memory/paging.c.s

chroma/system/memory/physmem.o: chroma/system/memory/physmem.c.o

.PHONY : chroma/system/memory/physmem.o

# target to build an object file
chroma/system/memory/physmem.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/physmem.c.o
.PHONY : chroma/system/memory/physmem.c.o

chroma/system/memory/physmem.i: chroma/system/memory/physmem.c.i

.PHONY : chroma/system/memory/physmem.i

# target to preprocess a source file
chroma/system/memory/physmem.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/physmem.c.i
.PHONY : chroma/system/memory/physmem.c.i

chroma/system/memory/physmem.s: chroma/system/memory/physmem.c.s

.PHONY : chroma/system/memory/physmem.s

# target to generate assembly for a file
chroma/system/memory/physmem.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/memory/physmem.c.s
.PHONY : chroma/system/memory/physmem.c.s

chroma/system/rw.o: chroma/system/rw.c.o

.PHONY : chroma/system/rw.o

# target to build an object file
chroma/system/rw.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/rw.c.o
.PHONY : chroma/system/rw.c.o

chroma/system/rw.i: chroma/system/rw.c.i

.PHONY : chroma/system/rw.i

# target to preprocess a source file
chroma/system/rw.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/rw.c.i
.PHONY : chroma/system/rw.c.i

chroma/system/rw.s: chroma/system/rw.c.s

.PHONY : chroma/system/rw.s

# target to generate assembly for a file
chroma/system/rw.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/rw.c.s
.PHONY : chroma/system/rw.c.s

chroma/system/serial.o: chroma/system/serial.c.o

.PHONY : chroma/system/serial.o

# target to build an object file
chroma/system/serial.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/serial.c.o
.PHONY : chroma/system/serial.c.o

chroma/system/serial.i: chroma/system/serial.c.i

.PHONY : chroma/system/serial.i

# target to preprocess a source file
chroma/system/serial.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/serial.c.i
.PHONY : chroma/system/serial.c.i

chroma/system/serial.s: chroma/system/serial.c.s

.PHONY : chroma/system/serial.s

# target to generate assembly for a file
chroma/system/serial.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/system/serial.c.s
.PHONY : chroma/system/serial.c.s

chroma/video/draw.o: chroma/video/draw.c.o

.PHONY : chroma/video/draw.o

# target to build an object file
chroma/video/draw.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/draw.c.o
.PHONY : chroma/video/draw.c.o

chroma/video/draw.i: chroma/video/draw.c.i

.PHONY : chroma/video/draw.i

# target to preprocess a source file
chroma/video/draw.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/draw.c.i
.PHONY : chroma/video/draw.c.i

chroma/video/draw.s: chroma/video/draw.c.s

.PHONY : chroma/video/draw.s

# target to generate assembly for a file
chroma/video/draw.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/draw.c.s
.PHONY : chroma/video/draw.c.s

chroma/video/print.o: chroma/video/print.c.o

.PHONY : chroma/video/print.o

# target to build an object file
chroma/video/print.c.o:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/print.c.o
.PHONY : chroma/video/print.c.o

chroma/video/print.i: chroma/video/print.c.i

.PHONY : chroma/video/print.i

# target to preprocess a source file
chroma/video/print.c.i:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/print.c.i
.PHONY : chroma/video/print.c.i

chroma/video/print.s: chroma/video/print.c.s

.PHONY : chroma/video/print.s

# target to generate assembly for a file
chroma/video/print.c.s:
	$(MAKE) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/chroma/video/print.c.s
.PHONY : chroma/video/print.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kernel.elf"
	@echo "... chroma/kernel.o"
	@echo "... chroma/kernel.i"
	@echo "... chroma/kernel.s"
	@echo "... chroma/system/cpu.o"
	@echo "... chroma/system/cpu.i"
	@echo "... chroma/system/cpu.s"
	@echo "... chroma/system/drivers/keyboard.o"
	@echo "... chroma/system/drivers/keyboard.i"
	@echo "... chroma/system/drivers/keyboard.s"
	@echo "... chroma/system/interrupts.o"
	@echo "... chroma/system/interrupts.i"
	@echo "... chroma/system/interrupts.s"
	@echo "... chroma/system/memory/paging.o"
	@echo "... chroma/system/memory/paging.i"
	@echo "... chroma/system/memory/paging.s"
	@echo "... chroma/system/memory/physmem.o"
	@echo "... chroma/system/memory/physmem.i"
	@echo "... chroma/system/memory/physmem.s"
	@echo "... chroma/system/rw.o"
	@echo "... chroma/system/rw.i"
	@echo "... chroma/system/rw.s"
	@echo "... chroma/system/serial.o"
	@echo "... chroma/system/serial.i"
	@echo "... chroma/system/serial.s"
	@echo "... chroma/video/draw.o"
	@echo "... chroma/video/draw.i"
	@echo "... chroma/video/draw.s"
	@echo "... chroma/video/print.o"
	@echo "... chroma/video/print.i"
	@echo "... chroma/video/print.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

